# Generated by Django 5.1.1 on 2024-10-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('file_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_phone_number', models.CharField(max_length=15)),
                ('emp_personal_email', models.EmailField(max_length=254, unique=True)),
                ('emp_address_line_1', models.CharField(max_length=255)),
                ('emp_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_city', models.CharField(max_length=100)),
                ('emp_state', models.CharField(max_length=100)),
                ('emp_zip', models.CharField(max_length=20)),
                ('emp_country', models.CharField(max_length=100)),
            ],
        ),
    ]
