# Generated by Django 5.1.1 on 2024-09-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
