# Generated by Django 5.1.1 on 2024-09-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='file',
        ),
        migrations.AddField(
            model_name='contact',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
