# Generated by Django 5.1.1 on 2024-10-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_file_contact_file_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='file_url',
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
